### ISSUE TITLE
Repo down or missing: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

### ISSUE THREAD

**Issue by Engineer-UA** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#114]
Hi!
I encounter the problem right on the second step of installation:
Repo down or missing: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

Have any ideas, what the problem is?

**Comment by itoffshore** [comment]
It is probably `iptables` blocking `tcp` port `443` outbound

**Comment by marketsystems** [comment]
Thats a pretty poor answer....

On my server at least i get that error because of the certificate on github is not being allowed by the wget command. The install script uses wget to retrieve include_files.txt 

(for ssl certs that dont validate i normally have to add --no-check-certificate to wget before it will work)

Solution for me:

vi $HOME/.wgetrc

add the line:

check_certificate=off

and save... all good now

**Comment by mitchellkrogza** [comment]
The repo is not down at all, possible there was a github outage when you
tried but if you can actually visit this repo to comment on the issue it
shows its very much alive and kicking.

**Comment by mitchellkrogza** [comment]
@marketsystems for some reason the github email did not display your full comments, another bug, but I've never encountered nor seen what you are describing and I use wget all the time on github, most strange

**Comment by marketsystems** [comment]
@mitchellkrogza I never had that issue with wget before this particular server. For some reason on my current dedicated server (is still  on centos6) wget is very strict at checking and will disallow access for ssl requests unless the certificate is a perfect match (gives error that name of cert is www.github.com not the domain specified in ur conf file). Not sure why might be a default config for that linux version or something to do with my particular ssl config. 

Buy anyway the fix is to add .wgetrc file in the root users home directory with those contents, then everything works perfectly..

**Comment by itoffshore** [comment]
these errors are fixed by installing `ca-certificates`

**Comment by marketsystems** [comment]
I checked, tried to install ca-certificates:

Package ca-certificates-2017.2.14-65.0.1.el6_9.noarch already installed and latest version

Maybe out of date, or maybe doesnt make a difference. Cant confirm either way :D

**Comment by mitchellkrogza** [comment]
@marketsystems that's strange but thanks for noting the fix for older CentOS users. I think with the way SSL is going it's going to become even more difficult in the months ahead for older distro's.

**Comment by marketsystems** [comment]
the big plus point of course... is once you do get this installed the blocker works extremely well wish i had done this a long time ago! very good job mate

**Comment by mitchellkrogza** [comment]
@marketsystems thanks so much and so glad to hear it's working well for you, have a great Christmas and all the best for 2018.
