### ISSUE TITLE
Which file i can edit to whitelist ip from rate limit rule are for DDOS filter?

### ISSUE THREAD

**Issue by tttungs** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#20]
Hi,
botblocker-nginx-settings.conf there have rule to rate limit as recommend for wordpress site is 90 request per second will be fine, but i'm using magento so i'm confuse which value is suiable for this or can i add ip to whitelist to ignore this rule somehow.

> limit_req_zone $binary_remote_addr zone=flood:50m rate=90r/s;
> limit_conn_zone $binary_remote_addr zone=addr:50m;

I can see there have a whitelist-ips.conf but it only work for limit bad bot.
Thanks.

**Comment by mitchellkrogza** [comment]
Simply edit / tweak the file https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/botblocker-nginx-settings.conf to suit your settings. Remember that if you are seeing yourself hitting rate limiting then all outside visitors to your site will experience the same thing as you so whitelisting is not even an option. Just tweak the settings to increase them so that rate limiting with normal visitations never kicks in. 

Remember that you can tweak botblocker-nginx-settings.conf to suit your needs and it won't get overwritten when you pull updates. 

So start off trying something like this below and monitor your logs in real time while hitting page after page on your site like a normal visitor might do. If you see rate limiting kick in then up the values. Remember to reload Nginx every time you change these settings.

```
limit_req_zone $binary_remote_addr zone=flood:50m rate=130r/s;
limit_conn_zone $binary_remote_addr zone=addr:50m;
```

**Comment by tttungs** [comment]
I will try that , thanks for your helps.

**Comment by rslonik** [comment]
I have another limit_req_zone conf file in conf.d and the way I managed to apply the whitelist-ip.conf to it was with a map:

```
map $ratelimited $login_limit_addr {
    0 "";  # Whitelisted IPs get empty string
    1 $binary_remote_addr;  # Everyone else gets normal limiting
}
limit_req_zone $login_limit_addr zone=login_rate:10m rate=10r/m;
```

**Comment by itoffshore** [comment]
if you have full control of your server - you will get much better performance by:

- `nginx` logs http `444` for blocked requests detected by UBBB
- `fail2ban` with `nftables` / `ipsets` does the actual blocking

This way `nginx` is only pattern matching a few times per bad ip

With `nftables` you can block bad ip's at the `ingress` level (i.e before the packets hit `conntrack` (connection tracking) - the overhead for blocking thousands of ip's is practically zero

For best performance with `fail2ban` use `journalmatch = _TRANSPORT=kernel` (so you do not need to log to a file & use an additional python library to parse it)
