### ISSUE TITLE
Seamonkey completely blocked

### ISSUE THREAD

**Issue by aumouth** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#21]
globalblacklist.conf
Version 2.2017.05

https://www.seamonkey-project.org/ is completely blocked via "~*SeaMonkey" 3;

SeaMonkey looks a completely reasonable and benign browser. Is its blocking an error?

**Comment by mitchellkrogza** [comment]
Thanks @aumouth fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/cabd8fd4994073630da09eb772c2f60f50fa85ef unofrtunately a few remnants remain in the bad bots list which originated from some very early lists I started with. Please notify me of any more normal browsers in the list that should not be blocked. They are listed in lines 214 > 683 of https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/globalblacklist.conf
