### ISSUE TITLE
How to update to new Build latest release

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#27]
Please let me know that How to update to new Build latest release?

**Comment by mitchellkrogza** [comment]
Read the configuration instructions they are very detailed and I took a lot of time writing them

**Comment by mitchellkrogza** [comment]
There is a new major update coming tomorrow for the Nginx Blocker today there was only a major update to the Apache blocker

**Comment by Nirjonadda** [comment]
@mitchellkrogza with /bots.d/blacklist-ips.conf include file to block their IP addresses?

STEP 10: UPDATING THE NGINX BAD BOT BLOCKER, Only files globalblacklist.conf replacing? no need to new files botblocker-nginx-settings.conf, blockbots.conf ... other etc files?

**Comment by mitchellkrogza** [comment]
All you do is pull the new globalblacklist.conf as per step 10 of updating. 

All the other files are now include files and can be customized to your liking, there is no need to update them only the globalblacklist.conf is required

**Comment by mitchellkrogza** [comment]
@Nirjonadda  Please be aware there is a new major version update happening today that is going to require some new include files otherwise Nginx will fail reload without them. Please check later today and read the new configuration instructions which will show you which additional include files need to be downloaded to /bots.d/ folder.

**Comment by mitchellkrogza** [comment]
Please see important major update released today
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/releases/tag/2017-04-20.Build-340
