### ISSUE TITLE
[User-Agent] Anomaly:Header:User-Agent - Fake Google Bot

### ISSUE THREAD

**Issue by Eckybrazzz** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#280]
Cloudflare Firewalll catches fake Google bot

```
{
  "id": "4f795b3b9e76c1a2",
  "country": "US",
  "ip": "52.203.142.240",
  "protocol": "HTTP/2",
  "method": "GET",
  "host": "<snipped>",
  "user_agent": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
  "uri": "/",
  "request_duration": 8999680,
  "triggered_rule_ids": [
    "100035"
  ],
  "action": "block",
  "cloudflare_location": "IAD",
  "occurred_at": "2019-07-17T04:08:44.09Z",
  "rule_detail": [
    {
      "id": "",
      "description": "REMOTE_ADDR"
    }
  ],
  "rule_message": "Anomaly:Header:User-Agent - Fake Google Bot",
  "type": "waf",
  "rule_id": "100035",
  "zone_id": "<snipped>",
  "cookie": ""
}
```

## Is this for Addition / Removal?

 - [x] Addition
 - [ ] Removal
 - [ ] Keep a watch on this one

**Comment by Eckybrazzz** [comment]
3.86.232.124 | US
52.87.213.12 | US
To add also

**Comment by gutitti** [comment]
Hello sir, i found ithemes security plugin using ip for scan website

    35.175.205.111
    34.229.141.32
    52.203.142.240 -> blocked
    52.87.213.12 -> blocked
    184.73.140.53
    18.206.213.51

https://help.ithemes.com/hc/en-us/articles/360007145634-What-Do-The-Malware-Scan-Errors-Mean-

but i can't add it to custom whitelist.conf because nginx: [warn] duplicate network "52.87.213.12", value: "0", old value: "1"

so i must manually edited globalblacklist.conf every time update
any solution ?
