### ISSUE TITLE
[BUG] (Can't whitelist my server IP)

### ISSUE THREAD

**Issue by nsgoyat** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#329]
Hey Mitchel,
I've been using your tool for more than 2 years with my NGINX installations and totally loving it. Thanks for this gem.

Actually, I started using a [Cache Warmer](https://github.com/khromov/sitemap-cache-warmer) recently which will simply visit my site's URLs listed in the Sitemap and regenerate the "Page Cache" for all those URLs, if they aren't cached already.

I use the following command to run the Cache Warmer:
`php "/var/www/example.com/htdocs/warm.php" key="xyzzzzzz" url="https://example.com/sitemap.xml"`

Then I checked my `examplecom.error.log` file from `/var/log/nginx/` and found the following entries:
```
2019/12/22 16:38:01 [error] 39016#39016: *2538 limiting requests, excess: 200.480 by zone "flood", client: 172.105.47.10, server: example.com, request: "GET /jawahar-navodaya-vidyalaya-class-6-admission/ HTTP/1.0", host: "example.com"
2019/12/22 16:38:01 [error] 39016#39016: *2539 limiting requests, excess: 200.120 by zone "flood", client: 172.105.47.10, server: example.com, request: "GET /jee-admit-card/ HTTP/1.0", host: "example.com"
2019/12/22 16:38:01 [error] 39016#39016: *2540 limiting requests, excess: 200.120 by zone "flood", client: 172.105.47.10, server: example.com, request: "GET /jee-main-result/ HTTP/1.0", host: "example.com"
2019/12/22 16:38:01 [error] 39016#39016: *2542 limiting requests, excess: 200.400 by zone "flood", client: 172.105.47.10, server: example.com, request: "GET /jeecup-application-form/ HTTP/1.0", host: "example.com"
2019/12/22 16:38:01 [error] 39016#39016: *2543 limiting requests, excess: 200.040 by zone "flood", client: 172.105.47.10, server: example.com, request: "GET /jeecup-result/ HTTP/1.0", host: "example.com"
```

So, I tried to whitelist my server IP by adding it to `/etc/nginx/bot.d/whitelist-ips.conf` like the following:
`172.105.47.10		0;`

Restarted the server after adding the above line & saving the file but the server IP is still getting blocked while processing Cache Warmer request. I am using the latest NGINX on Ubuntu 18.04 LTS with almost default nginx.conf file.

**Comment by mitchellkrogza** [comment]
Hi @nsgoyat glad it helps you :+1: 

Just tweak the settings for the flood zone until you find a good setting > botblocker-nginx-settings.conf
`limit_req_zone $binary_remote_addr zone=flood:50m rate=90r/s;`

Try `200r/s` and keep increasing by 20 or so until you find a nice rate for it.

**Comment by 0xorio** [comment]
Hey. I've also encountered this issue. Addresses in whitelist-ips.conf are not considered when applying the bot2_reqlimitip request limitation. @mitchellkrogza, your suggestion to change the limitation settings does not solve the problem. As workaround, I've added my server's address to the super whitelist in blockbots.conf.

**Comment by rslonik** [comment]
I have another limit_req_zone conf file in conf.d and the way I managed to apply the whitelist-ip.conf to it was with a map:

```
map $ratelimited $login_limit_addr {
    0 "";  # Whitelisted IPs get empty string
    1 $binary_remote_addr;  # Everyone else gets normal limiting
}
limit_req_zone $login_limit_addr zone=login_rate:10m rate=10r/m;
```

**Comment by vlauciani** [comment]
I’ve been investigating whether it’s possible to add an IP whitelist for the `flood` limit zone, but after testing and reviewing the NGINX docs, it looks like this isn’t feasible without modifying the Bot Blocker configuration itself.

Here’s why:
- The flood zone is defined like this in `botblocker-nginx-settings.conf`:
```
limit_req_zone $binary_remote_addr zone=flood:50m rate=90r/s;
```
This means the request key is fixed to `$binary_remote_addr`.

- NGINX rate limiting works by mapping the request key to a counter.
The only way to “whitelist” is to use a variable key that can be set to an empty value (requests with an empty key are not counted).
Because `$binary_remote_addr` is hardcoded here, it cannot be made empty for certain IPs without redefining the zone.

- Adding a separate `map` or whitelist block does not override the key used in an already-defined `limit_req_zone`.
The only way to support an IP whitelist is to either:
  - Change the `limit_req_zone` directive to use a variable (e.g., `$limit`) instead of `$binary_remote_addr`, or
  - Use alternative approaches like separate server blocks or `limit_req_dry_run on;` for specific IPs.

So, out of the box, there is no way to whitelist IPs for the `flood` zone without editing the Bot Blocker config to use a custom variable for the key.
