### ISSUE TITLE
[CCBot/2.0 (http://commoncrawl.org/faq/)] (An excellent nonprofit project that is blocked)

### ISSUE THREAD

**Issue by rbjarnason** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#487]
## Paste the full User-Agent String here

```
CCBot/2.0 (http://commoncrawl.org/faq/)
```

## Is this for Addition / Removal?

 - [ ] Addition
 - [x] Removal
 - [ ] Keep a watch on this one

## Did the User-Agent request robots.txt first?

 - [ x] Yes
 - [ ] No

## Additional information

Thank you for your excellent project that has been a great help to us, but we also noticed you blocked CCBot. CommonCrawl is an excellent nonprofit project that we use a much ourselves. CCBot respects both robots.txt and Crawl-Delay.

**Comment by mitchellkrogza** [comment]
Will not be removed unfortunately CCBot has been here since inception. You can happily and easily unblock it yourself in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/bots.d/blacklist-user-agents.conf but removing it will upset a LOT of users and there are thousands.

Also see

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/515
