### ISSUE TITLE
Duplicate network

### ISSUE THREAD

**Issue by bazalt** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#80]
Hi,

Just want to point out that a redundant IP causes Nginx to throw a warning:
nginx: [warn] duplicate network "65.192.0.0/11", value: "0", old value: "0" in /etc/nginx/bots.d/blacklist-ips.conf:190

```
	65.192.0.0/11		0;
	65.192.0.0/11		0;
```
Thanks for your amazing work

**Comment by mitchellkrogza** [comment]
Thanks for your support and so glad this project is helping you. I am aware
of that Nginx WARN error on a duplicate IP, luckily Nginx is smart enough
to still reload and not a fail a reload due to that. Future versions will
address this somehow to make sure no dupes exist in any of the include
files, I'm sure @itoffshore could help with that feature at some point in
the setup-ngblocker script.

Happy bot and bad referrer blocking.

Kind Regards
Mitch

**Comment by bazalt** [comment]
By the way, what is the relation between your Nginx blocker and @[mariusv's](https://github.com/mariusv/nginx-badbot-blocker) ?

**Comment by mitchellkrogza** [comment]
VERSION_2 of Marius V's repo is mine. Same as this but this one in the
mainstream repo and has many more features. Thos repo is always the most up
to date and it has the great setup, install and update scripts. This repo
was also made into a package in the Alpine Linux distro all done by Stuart
Cardall @itoffshore

**Comment by bazalt** [comment]
Thanks Mitch.
